### ISSUE TITLE
QM9 dataset processing issues

### ISSUE THREAD

**Issue by wconnell** [BioinfoMachineLearning/bio-diffusion#3]
ok, I encountered 2 issues before I got things training on QM9 that maybe you missed because your datasets are already downloaded/processed. additional reply per #1.

1. args are passed out of order here: https://github.com/BioinfoMachineLearning/bio-diffusion/blob/3751670591bcf40a439c3638a42b6e18683fb0e9/src/datamodules/components/edm/rdkit_functions.py#L70 this should read 
```
mol = build_molecule(torch.tensor(positions), torch.tensor(atom_type), dataset_info, charges)
```
2. error trace back from here: https://github.com/BioinfoMachineLearning/bio-diffusion/blob/3751670591bcf40a439c3638a42b6e18683fb0e9/src/datamodules/components/edm/__init__.py#L70 due to no `bonds1` key in `dataset_info`. I fixed it here, maybe there is a better place though (and maybe there is a more correct method? I'm not very familiar with the data): https://github.com/BioinfoMachineLearning/bio-diffusion/blob/3751670591bcf40a439c3638a42b6e18683fb0e9/src/datamodules/components/edm/rdkit_functions.py#L134
```
from src.datamodules.components.edm import get_bond_length_arrays
...
# retrieve dataset smiles only for the QM9 dataset currently
if dataset_smiles_list is None and "QM9" in dataset_info["name"]:
    bonds = get_bond_length_arrays(self.dataset_info["atom_encoder"])
    self.dataset_info["bonds1"], self.dataset_info["bonds2"], self.dataset_info["bonds3"] = (
            bonds[0], bonds[1], bonds[2]
        )
    self.dataset_smiles_list = retrieve_qm9_smiles(self.dataset_info, data_dir)
```

I'm happy to push changes if you like. Just lmk!

**Comment by amorehead** [comment]
Once again, thanks, @wconnell, for identifying these lingering oversights of mine in our training code! You are correct. I was not able to see these errors because my copy of the QM9 dataset is already processed. I have just finished [pushing](https://github.com/BioinfoMachineLearning/bio-diffusion) the fixes you described above to `main`. If you have any other issues arise, please let me know and I would be happy to include fixes for them.
