### ISSUE TITLE
there might be errors in the egnn code

### ISSUE THREAD

**Issue by charlotte0104** [BioinfoMachineLearning/bio-diffusion#6]
i found 6 unresolved references in the code of egnn,just like the picture
![error](https://github.com/BioinfoMachineLearning/bio-diffusion/assets/78527796/be3e7383-b5bb-49e4-b0d6-1d9bcec3e61b)
Perhaps you can provide a correct version，thanks！
 I would greatly appreciate it if you could help

**Comment by amorehead** [comment]
Hello. Thank you for pointing this out. The `egnn.py` implementation we include in this repository was from early on in GCDM's development. Since then, we have not maintained or updated this EGNN encoder. If I recall correctly, it was sourced from lucidrain's implementation: https://github.com/lucidrains/egnn-pytorch. If so, these errors may simply be "warnings" since these areas of the `egnn.py` code aren't reached in all cases (if I'm remembering correctly).

**Comment by amorehead** [comment]
I recommend commenting out these lines and any other surrounding code (e.g., clauses). If PyCharm (as shown above) is still not letting you run the code, let me know.

**Comment by amorehead** [comment]
Hi, @charlotte0104. If you have any follow-up questions, please let me know. Otherwise, I will be closing this issue for now.
