### ISSUE TITLE
GEOM-Drugs train bio-diffusion

### ISSUE THREAD

**Issue by 18hfliu** [BioinfoMachineLearning/bio-diffusion#9]
First，When I run this command python3 src/train.py experiment=geom_mol_gen_ddpm.yaml, set the parameter trainer.devices=1 datamodule.dataloader_cfg.batch_size=512 and compare trainer.devices=8 datamodule.dataloader_cfg.batch_size=512, the following progress bar appears. 
Epoch 0/2999 ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589/12170
Why is the total number of steps in a batch 12170?
Second, Why does the error “Skipping training batch with index 10795 due to OOM error” occur after training for a period of time?

**Comment by amorehead** [comment]
Hi, @18hfliu.

The reason the total number of steps in a batch is 12,170 is that the GEOM-Drugs dataset consists of 430k unique molecules, where for each molecule several conformers were originally generated (and then these conformers were filtered down to the 30 lowest-energy conformations). This in principle leaves 430,000 × 30 = 12,900,000 conformers available for training, where around half of these conformers are in practice dropped following the same input dataloading pipeline logic as in the [EDM](https://github.com/ehoogeboom/e3_diffusion_for_molecules) repository. This leaves around 6 million conformers available for training in total (e.g., 12,170 × 512 batch size = 6,231,040).

When it comes to increasing the number of GPUs, I have not personally tested multi-GPU training on the GEOM-Drugs dataset using PyTorch Lightning. In principle, it should work out of the box given Lightning's support for most Dataloader sampling techniques. However, I cannot guarantee it will work at this moment (n.b., you might try upgrading your version of Lightning to see if this would install any relevant bugfixes in Lightning's core dataloading logic). It's also possible that the progress bar is displaying the total number of batches after synchronizing it with each GPU rank. In which case, around 12k batches is how batches one would expect all the GPU ranks to process altogether.

Regarding the error message above, this comes from a simple wrapper around the forward pass of the model that skips a training batch (on any particular GPU rank) if that GPU rank runs out of GPU memory during its forward pass for a particular training example. This can be quite handy when training with a single GPU, as it prevents the entire training run from crashing upon performing a forward pass on an unusually large training molecule. Note that, when training with multiple GPUs via DDP (as is common with PyTorch Lightning models), having one GPU skip a batch while others instead perform their forward pass can cause the GPU ranks to hit a deadlock, since the ranks can become out-of-sync with each other (see https://github.com/Lightning-AI/pytorch-lightning/issues/5243#issuecomment-1753486797 for more details).

**Comment by amorehead** [comment]
Hi, @18hfliu. If you have any follow-up questions, please feel free to re-open this issue or create a new one. In the meantime, I will be closing this issue.

**Comment by 18hfliu** [comment]
Ok, thank you
